version: "2"

services:
  acntech_bind:
    build: .
    image: acntech/bind:latest
    container_name: acntech-bind
    hostname: bind
    domainname: acntech.internal
    ports:
      - "53:53/tcp"
      - "53:53/udp"
